/* eslint-disable */
// Generated by website/scripts/generateMonacoPreloads.cjs — do not edit.
// Re-run via docusaurus.config.ts (ensureMonacoPreloadManifest) or:
//   node website/scripts/generateMonacoPreloads.cjs

export const monacoPreloadManifest = {
  preloadPaths: [
    'loader.js',
    'editor/editor.main.js',
    'nls.messages-loader.js',
    'monaco.contribution-DO3azKX8.js',
    'monaco.contribution-qLAYrEOP.js',
    'monaco.contribution-EcChJV6a.js',
    'monaco.contribution-D2OdxNBt.js',
    'basic-languages/monaco.contribution.js',
    'editor.api-CalNCsUg.js',
    'workers-DcJshg-q.js',
  ],
  prefetchPaths: [
    'assets/editor.worker-Be8ye1pW.js',
    'assets/ts.worker-CMbG-7ft.js',
    'tsMode-CZz1Umrk.js',
    'typescript-DfOrAzoV.js',
  ],
} as const;

export const MONACO_CDN_VS =
  'https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/min/vs';
