/**
 * Generates agent skill references (.agents/skills/<skill>/references/*.md)
 * from the docs, so skills stay in sync with the site without shipping MDX.
 *
 * Each skill lists the docs it needs in `references.json`:
 *
 *   { "frameworks": ["react", "vue"], "docs": { "useSuspense.md": "docs/core/api/useSuspense.md" } }
 *
 * The first framework with the page writes `<name>.md`; later ones write
 * `<name>.<framework>.md` only when their page differs.
 *
 * `"skills": ["other-skill"]` bundles another skill so this one works without
 * it installed: its SKILL.md body becomes `references/other-skill.md` and its
 * other files (references, scripts) are copied under `references/other-skill/`.
 *
 * Usage: node website/framework-docs/skillReferences.mjs [--check]
 */
import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

import { ROOT, SITE, docToMarkdown, rel, routeOf } from './docsToMarkdown.mjs';

const { FM } = createRequire(import.meta.url)('./index.js');

const SKILLS = path.join(ROOT, '.agents/skills');
const MANIFEST = 'references.json';
const GENERATED = 'Generated by `yarn build:skills` from';
const MD = /\.mdx?$/;

/** content marked as generated, in that file type's comment syntax */
function withHeader(file, content) {
  const text = `${GENERATED} ${rel(file)}. Edit the source, not this file.`;
  if (MD.test(file)) return `<!-- ${text} -->\n\n${content}`;
  if (!/\.[cm]?[jt]s$/.test(file))
    throw new Error(`${rel(file)}: can't mark this file type as generated`);
  // after a shebang, which must stay the first line
  const [, shebang = '', rest] = content.match(/^(#!.*\n)?([\s\S]*)$/);
  return `${shebang}// ${text}\n${rest}`;
}

/** Every file under dir, recursively, following symlinks */
const walk = dir =>
  fs.existsSync(dir) ?
    fs
      .readdirSync(dir, { recursive: true })
      .map(f => path.join(dir, f))
      .filter(f => fs.statSync(f).isFile())
  : [];

/** The header is the first line, or the second after a shebang */
const isGenerated = content =>
  content.split('\n', 2).some(line => line.includes(GENERATED));

/** Content ignoring the header and which framework's docs links point to */
const comparable = content =>
  content?.replace(/^.*\n/, '').replaceAll(`${SITE}/vue/`, `${SITE}/docs/`);

const generated = new Map();

/** Map of reference path -> content for one skill */
function generateSkill(skillDir) {
  if (!generated.has(skillDir))
    generated.set(skillDir, generateUncached(skillDir));
  return generated.get(skillDir);
}

function generateUncached(skillDir) {
  const {
    frameworks,
    docs,
    skills = [],
  } = JSON.parse(fs.readFileSync(path.join(skillDir, MANIFEST), 'utf8'));
  const out = new Map();
  for (const framework of frameworks) {
    // links between pages in the same skill stay local
    const localRoutes = new Map();
    for (const [name, doc] of Object.entries(docs)) {
      const file = path.join(ROOT, doc);
      // generated references aren't sources: they may not be regenerated yet
      if (!doc.startsWith('docs/'))
        throw new Error(`${rel(skillDir)}/${MANIFEST}: ${doc} is not in docs/`);
      if (!fs.existsSync(file))
        throw new Error(`${rel(skillDir)}/${MANIFEST}: ${doc} does not exist`);
      if (!path.basename(file).startsWith('_'))
        localRoutes.set(routeOf(file, framework), name);
    }
    const resolveRoute = url => {
      const [, route, hash = ''] = url.match(/^([^#]*)(#.*)?$/);
      return localRoutes.has(route) ?
          `./${localRoutes.get(route)}${hash}`
        : SITE + url;
    };
    for (const [name, doc] of Object.entries(docs)) {
      const body = docToMarkdown(path.join(ROOT, doc), framework, {
        resolveRoute,
      });
      if (!body) continue;
      const content = `<!-- ${GENERATED} ${doc} (${framework}). Edit the source doc, not this file. -->\n\n${body}`;
      const primary = path.join(skillDir, 'references', name);
      // the first framework that has the page writes `<name>.md`
      if (!out.has(primary)) out.set(primary, content);
      else if (comparable(out.get(primary)) !== comparable(content))
        out.set(primary.replace(MD, `.${framework}.md`), content);
    }
  }
  for (const skill of skills)
    bundleSkill(path.join(SKILLS, skill), skillDir, out);
  return out;
}

/** Adds a copy of sourceDir's skill to out, under skillDir's references */
function bundleSkill(sourceDir, skillDir, out) {
  const skill = path.basename(sourceDir);
  const dest = path.join(skillDir, 'references', skill);
  const skillMd = path.join(sourceDir, 'SKILL.md');
  if (!fs.existsSync(skillMd))
    throw new Error(`${rel(skillDir)}/${MANIFEST}: no skill ${skill}`);
  const body = fs
    .readFileSync(skillMd, 'utf8')
    .replace(FM, '')
    .trimStart()
    // relative links now resolve from references/, next to the copied files;
    // fenced code (odd split indexes) is left as is
    .split(/(^```[\s\S]*?^```)/m)
    .map((part, i) =>
      i % 2 ? part : (
        part.replace(/\]\((?![a-z]+:|[#/])(?:\.\/)?/g, `](./${skill}/`)
      ),
    )
    .join('');
  out.set(`${dest}.md`, withHeader(skillMd, body));
  // its generated references come from their sources, so they can't be stale
  const sourceGenerated =
    fs.existsSync(path.join(sourceDir, MANIFEST)) ?
      generateSkill(sourceDir)
    : new Map();
  for (const [file, content] of sourceGenerated)
    out.set(path.join(dest, path.relative(sourceDir, file)), content);
  for (const file of walk(sourceDir)) {
    const name = path.relative(sourceDir, file);
    const content = fs.readFileSync(file, 'utf8');
    if (name === 'SKILL.md' || name === MANIFEST || isGenerated(content))
      continue;
    out.set(path.join(dest, name), withHeader(file, content));
  }
}

/** Generated files currently on disk, by path */
const generatedFiles = dir =>
  new Map(
    walk(dir)
      .filter(f => !fs.lstatSync(f).isSymbolicLink())
      .map(f => [f, fs.readFileSync(f, 'utf8')])
      .filter(([, content]) => isGenerated(content)),
  );

/** [file, content] for every file to write, with content null to delete */
const changes = [];
for (const skill of fs.readdirSync(SKILLS).sort()) {
  const skillDir = path.join(SKILLS, skill);
  if (!fs.existsSync(path.join(skillDir, MANIFEST))) continue;
  const out = generateSkill(skillDir);
  const current = generatedFiles(path.join(skillDir, 'references'));
  for (const file of current.keys())
    if (!out.has(file)) changes.push([file, null]);
  for (const [file, content] of out)
    if (current.get(file) !== content) changes.push([file, content]);
}

if (process.argv.includes('--check')) {
  if (changes.length) {
    console.error(
      `Skill references are out of date with the docs or bundled skills:\n  ${changes.map(([f]) => rel(f)).join('\n  ')}\nRun \`yarn build:skills\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log('Skill references are up to date.');
} else {
  for (const [file, content] of changes) {
    // also replaces a symlink left from before references were generated
    fs.rmSync(file, { force: true });
    if (content === null) continue;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
  console.log(`Updated ${changes.length} skill reference files.`);
}

const problems = fs.readdirSync(SKILLS).flatMap(skill => {
  const skillMd = path.join(SKILLS, skill, 'SKILL.md');
  const refs = path.join(SKILLS, skill, 'references');
  const text = fs.existsSync(skillMd) ? fs.readFileSync(skillMd, 'utf8') : '';
  const files = fs.existsSync(refs) ? fs.readdirSync(refs) : [];
  const manifest = path.join(SKILLS, skill, MANIFEST);
  const { frameworks = [] } =
    fs.existsSync(manifest) ?
      JSON.parse(fs.readFileSync(manifest, 'utf8'))
    : {};
  return [
    // links to references that no longer exist (renamed or removed docs)
    ...[...text.matchAll(/\]\((references\/[^)#\s]+)/g)]
      .map(([, link]) => link)
      .filter(link => !fs.existsSync(path.join(SKILLS, skill, link)))
      .map(link => `${rel(skillMd)} links to missing ${link}`),
    // symlinked docs ship raw MDX; list them in references.json instead
    ...files
      .filter(
        f => MD.test(f) && fs.lstatSync(path.join(refs, f)).isSymbolicLink(),
      )
      .map(f => `${rel(refs)}/${f} is a symlink; add it to ${MANIFEST}`),
    // agents only find framework variants if SKILL.md tells them to look
    ...frameworks
      .slice(1)
      .filter(fw => files.some(f => f.endsWith(`.${fw}.md`)))
      .filter(fw => !text.includes(`.${fw}.md`))
      .map(
        fw =>
          `${rel(skillMd)} needs a note to read \`<name>.${fw}.md\` instead of \`<name>.md\` for ${fw} projects`,
      ),
  ];
});
if (problems.length) {
  console.error(`Skill problems:\n  ${[...new Set(problems)].join('\n  ')}`);
  process.exit(1);
}
