/**
 * Generates agent skill references (.agents/skills/<skill>/references/*.md)
 * from the docs, so skills stay in sync with the site without shipping MDX.
 *
 * Each skill lists the docs it needs in `references.json`:
 *
 *   { "frameworks": ["react", "vue"], "docs": { "useSuspense.md": "docs/core/api/useSuspense.md" } }
 *
 * The first framework with the page writes `<name>.md`; later ones write
 * `<name>.<framework>.md` only when their page differs.
 *
 * Usage: node website/framework-docs/skillReferences.mjs [--check]
 */
import fs from 'node:fs';
import path from 'node:path';

import { frameworkInstance } from './docsInstances.js';
import { docToMarkdown, routeOf } from './docsToMarkdown.mjs';
import { ROOT, SITE, rel } from './site.mjs';

const SKILLS = path.join(ROOT, '.agents/skills');
const MANIFEST = 'references.json';
const HEADER = '<!-- Generated by `yarn build:skills` from';
const MD = /\.mdx?$/;

/**
 * Content ignoring the header, which framework's docs links point to, and the
 * table padding those links' lengths change
 */
const comparable = content =>
  content
    ?.replace(/^.*\n/, '')
    .replaceAll(
      `${SITE}/${frameworkInstance('vue').routeBasePath}/`,
      `${SITE}/${frameworkInstance('react').routeBasePath}/`,
    )
    .replace(/ {2,}/g, ' ')
    .replace(/-{3,}/g, '---');

/** Route of each skill doc -> its reference name, so links between them stay local */
const localRoutesFor = (docs, framework) =>
  new Map(
    Object.entries(docs)
      .filter(([, doc]) => !path.basename(doc).startsWith('_'))
      .map(([name, doc]) => [routeOf(path.join(ROOT, doc), framework), name]),
  );

/** Map of reference path -> content for one skill */
function generateSkill(skillDir) {
  const { frameworks, docs } = JSON.parse(
    fs.readFileSync(path.join(skillDir, MANIFEST), 'utf8'),
  );
  const out = new Map();
  // framework that rendered each file
  const renderedBy = new Map();
  for (const doc of Object.values(docs)) {
    // generated references aren't sources: they may not be regenerated yet
    if (!doc.startsWith('docs/'))
      throw new Error(`${rel(skillDir)}/${MANIFEST}: ${doc} is not in docs/`);
    if (!fs.existsSync(path.join(ROOT, doc)))
      throw new Error(`${rel(skillDir)}/${MANIFEST}: ${doc} does not exist`);
  }
  for (const framework of frameworks) {
    const localRoutes = localRoutesFor(docs, framework);
    const resolveRoute = url => {
      const [, route, hash = ''] = url.match(/^([^#]*)(#.*)?$/);
      return localRoutes.has(route) ?
          `./${localRoutes.get(route)}${hash}`
        : SITE + url;
    };
    for (const [name, doc] of Object.entries(docs)) {
      const body = docToMarkdown(path.join(ROOT, doc), framework, {
        resolveRoute,
      });
      if (!body) continue;
      const content = `${HEADER} ${doc} (${framework}). Edit the source doc, not this file. -->\n\n${body}`;
      const primary = path.join(skillDir, 'references', name);
      // the first framework that has the page writes `<name>.md`
      let file = primary;
      if (out.has(primary)) {
        if (comparable(out.get(primary)) === comparable(content)) continue;
        file = primary.replace(MD, `.${framework}.md`);
      }
      out.set(file, content);
      renderedBy.set(file, framework);
    }
  }
  // a framework's page links to that framework's version of other pages
  for (const [file, content] of out) {
    const framework = renderedBy.get(file);
    out.set(
      file,
      content.replace(
        /(\]\(\.\/)([^)#\s]+)\.md(?=[)#])/g,
        (link, open, name) =>
          (
            out.has(
              path.join(skillDir, 'references', `${name}.${framework}.md`),
            )
          ) ?
            `${open}${name}.${framework}.md`
          : link,
      ),
    );
  }
  return out;
}

/** Generated files currently on disk, by path */
function generatedFiles(dir) {
  if (!fs.existsSync(dir)) return new Map();
  return new Map(
    fs
      .readdirSync(dir)
      .filter(f => f.endsWith('.md'))
      .map(f => path.join(dir, f))
      .filter(f => !fs.lstatSync(f).isSymbolicLink())
      .map(f => [f, fs.readFileSync(f, 'utf8')])
      .filter(([, content]) => content.startsWith(HEADER)),
  );
}

/** [file, content] for every file to write, with content null to delete */
const changes = [];
for (const skill of fs.readdirSync(SKILLS).sort()) {
  const skillDir = path.join(SKILLS, skill);
  if (!fs.existsSync(path.join(skillDir, MANIFEST))) continue;
  const out = generateSkill(skillDir);
  const current = generatedFiles(path.join(skillDir, 'references'));
  for (const file of current.keys())
    if (!out.has(file)) changes.push([file, null]);
  for (const [file, content] of out)
    if (current.get(file) !== content) changes.push([file, content]);
}

if (process.argv.includes('--check')) {
  if (changes.length) {
    console.error(
      `Skill references are out of date with the docs:\n  ${changes.map(([f]) => rel(f)).join('\n  ')}\nRun \`yarn build:skills\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log('Skill references are up to date.');
} else {
  for (const [file, content] of changes) {
    // also replaces a symlink left from before references were generated
    fs.rmSync(file, { force: true });
    if (content === null) continue;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
  console.log(`Updated ${changes.length} skill reference files.`);
}

const problems = fs.readdirSync(SKILLS).flatMap(skill => {
  const skillMd = path.join(SKILLS, skill, 'SKILL.md');
  const refs = path.join(SKILLS, skill, 'references');
  const text = fs.existsSync(skillMd) ? fs.readFileSync(skillMd, 'utf8') : '';
  const files = fs.existsSync(refs) ? fs.readdirSync(refs) : [];
  const manifest = path.join(SKILLS, skill, MANIFEST);
  const { frameworks = [] } =
    fs.existsSync(manifest) ?
      JSON.parse(fs.readFileSync(manifest, 'utf8'))
    : {};
  return [
    // links to references that no longer exist (renamed or removed docs)
    ...[...text.matchAll(/\]\((references\/[^)#\s]+)/g)]
      .map(([, link]) => link)
      .filter(link => !fs.existsSync(path.join(SKILLS, skill, link)))
      .map(link => `${rel(skillMd)} links to missing ${link}`),
    // symlinked docs ship raw MDX; list them in references.json instead
    ...files
      .filter(
        f => MD.test(f) && fs.lstatSync(path.join(refs, f)).isSymbolicLink(),
      )
      .map(f => `${rel(refs)}/${f} is a symlink; add it to ${MANIFEST}`),
    // agents only find framework variants if SKILL.md tells them to look
    ...frameworks
      .slice(1)
      .filter(fw => files.some(f => f.endsWith(`.${fw}.md`)))
      .filter(fw => !text.includes(`.${fw}.md`))
      .map(
        fw =>
          `${rel(skillMd)} needs a note to read \`<name>.${fw}.md\` instead of \`<name>.md\` for ${fw} projects`,
      ),
  ];
});
if (problems.length) {
  console.error(`Skill problems:\n  ${[...new Set(problems)].join('\n  ')}`);
  process.exit(1);
}
