/**
 * Generates agent skill references (.agents/skills/<skill>/references/*.md)
 * from the docs, so skills stay in sync with the site without shipping MDX.
 *
 * Each skill lists the docs it needs in `references.json`:
 *
 *   { "frameworks": ["react", "vue"], "docs": { "useSuspense.md": "docs/core/api/useSuspense.md" } }
 *
 * The first framework writes `<name>.md`; later ones write
 * `<name>.<framework>.md` only when their page differs.
 *
 * Usage: node website/framework-docs/skillReferences.mjs [--check]
 */
import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

import { ROOT, SITE, docToMarkdown, rel, routeOf } from './docsToMarkdown.mjs';

const { frameworkInstance } = createRequire(import.meta.url)(
  './docsInstances.js',
);

const SKILLS = path.join(ROOT, '.agents/skills');
const MANIFEST = 'references.json';
const HEADER = '<!-- Generated by `yarn build:skills` from';
const MD = /\.mdx?$/;

/** Content ignoring the header and which framework's docs links point to */
const comparable = content =>
  content
    ?.replace(/^.*\n/, '')
    .replaceAll(
      `${SITE}/${frameworkInstance('vue').routeBasePath}/`,
      `${SITE}/${frameworkInstance('react').routeBasePath}/`,
    );

/** Map of reference path -> content for one skill */
function generateSkill(skillDir) {
  const { frameworks, docs } = JSON.parse(
    fs.readFileSync(path.join(skillDir, MANIFEST), 'utf8'),
  );
  const out = new Map();
  for (const framework of frameworks) {
    // links between pages in the same skill stay local
    const localRoutes = new Map();
    for (const [name, doc] of Object.entries(docs)) {
      const file = path.join(ROOT, doc);
      if (!fs.existsSync(file))
        throw new Error(`${rel(skillDir)}/${MANIFEST}: ${doc} does not exist`);
      if (!path.basename(file).startsWith('_'))
        localRoutes.set(routeOf(file, framework), name);
    }
    const resolveRoute = url => {
      const [, route, hash = ''] = url.match(/^([^#]*)(#.*)?$/);
      return localRoutes.has(route) ?
          `./${localRoutes.get(route)}${hash}`
        : SITE + url;
    };
    for (const [name, doc] of Object.entries(docs)) {
      const body = docToMarkdown(path.join(ROOT, doc), framework, {
        resolveRoute,
      });
      if (!body) continue;
      const content = `${HEADER} ${doc} (${framework}). Edit the source doc, not this file. -->\n\n${body}`;
      const primary = path.join(skillDir, 'references', name);
      if (framework === frameworks[0]) out.set(primary, content);
      else if (comparable(out.get(primary)) !== comparable(content))
        out.set(primary.replace(MD, `.${framework}.md`), content);
    }
  }
  return out;
}

/** Generated files currently on disk, by path */
function generatedFiles(dir) {
  if (!fs.existsSync(dir)) return new Map();
  return new Map(
    fs
      .readdirSync(dir)
      .filter(f => f.endsWith('.md'))
      .map(f => path.join(dir, f))
      .filter(f => !fs.lstatSync(f).isSymbolicLink())
      .map(f => [f, fs.readFileSync(f, 'utf8')])
      .filter(([, content]) => content.startsWith(HEADER)),
  );
}

/** [file, content] for every file to write, with content null to delete */
const changes = [];
for (const skill of fs.readdirSync(SKILLS).sort()) {
  const skillDir = path.join(SKILLS, skill);
  if (!fs.existsSync(path.join(skillDir, MANIFEST))) continue;
  const out = generateSkill(skillDir);
  const current = generatedFiles(path.join(skillDir, 'references'));
  for (const file of current.keys())
    if (!out.has(file)) changes.push([file, null]);
  for (const [file, content] of out)
    if (current.get(file) !== content) changes.push([file, content]);
}

if (process.argv.includes('--check')) {
  if (changes.length) {
    console.error(
      `Skill references are out of date with the docs:\n  ${changes.map(([f]) => rel(f)).join('\n  ')}\nRun \`yarn build:skills\` and commit the result.`,
    );
    process.exit(1);
  }
  console.log('Skill references are up to date.');
} else {
  for (const [file, content] of changes) {
    // also replaces a symlink left from before references were generated
    fs.rmSync(file, { force: true });
    if (content === null) continue;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
  console.log(`Updated ${changes.length} skill reference files.`);
}
