/* eslint-disable */
// Generated by website/scripts/generateMonacoPreloads.cjs — do not edit.
// Re-run via docusaurus.config.ts (ensureMonacoPreloadManifest) or:
//   node website/scripts/generateMonacoPreloads.cjs

export const monacoPreloadManifest = {
  preloadPaths: [
    'loader.js',
    'editor/editor.main.js',
    'json.worker-Bp7U0-9w.js',
    'css.worker-BInK4lsP.js',
    'html.worker-C1TNvQ72.js',
    'ts.worker-BLYAhMkX.js',
    'nls.messages-loader.js',
    'index-DZH_zysX.js',
    'monaco.contribution-C7tY_xnl.js',
    'editor-BdtEMBbM.js',
    'monaco.contribution-BuX2NvO2.js',
    'monaco.contribution-CY2lwFI8.js',
    'monaco.contribution-D1-wBxcq.js',
    'toggleHighContrast-DuqAmExZ.js',
    'basic-languages/monaco.contribution.js',
    'editorWorkerHost-B_VpI68A.js',
  ],
  prefetchPaths: [
    'assets/editor.worker-_vAIFJDs.js',
    'assets/ts.worker-g3pjEjl4.js',
    'tsMode-DB1GiNun.js',
    'typescript-BTLNeq8B.js',
  ],
} as const;

export const MONACO_CDN_VS =
  'https://cdn.jsdelivr.net/npm/monaco-editor@0.57.0/min/vs';
